### ISSUE TITLE
Verify & Publish hanging indefinitely.

### ISSUE THREAD

**Issue by zquestz** [mistswapdex/sonar#4]
When trying to "Verify & publish" a smart contract it hangs indefinitely when the args are correct. When the contract doesn't match, it errors out quickly as it should.

### Environment

* Operating System: Linux
* Blockscout Version/branch: Latest 

### Steps to reproduce

1. Go to address of smart contract.
2. Click "Verify & Publish"
3. Select "Via flattened source code"
4. Click "Next" 
5. Fill out details for the contract - ![image](https://user-images.githubusercontent.com/83898/172269925-05ed6296-9dae-4771-8ac1-bdc8ae59507b.png)
6. Click "Verify & publish"
7. Watch as it never completes if the data is correct. For incorrect contracts it errors as it should.

### Expected behaviour

Should successfully verify the contract.

### Actual behaviour

Hangs indefiniitely.

**Comment by RedWilly** [comment]
Hey @zquest having issue verifying my Smart Contract. 

Still Loading ....
