### ISSUE TITLE
Verify & Publish 

### ISSUE THREAD

**Issue by RedWilly** [mistswapdex/sonar#7]
Hey Mistswap having issue verifying my Smart Contract.

Still Loading 

Bytecode does not match, please try again.

**Comment by RedWilly** [comment]
this the contract - https://github.com/RedWilly/Cackles-Backend

**Comment by zquestz** [comment]
Just got it working for you!

https://sonar.cash/address/0xbad64f85727D27e67631BC1a5B6e339cd1830c4a/contracts

**Comment by RedWilly** [comment]
Thanks zquestz
